# being built in excel to be transfered here soon
Contestant.create(name: "Dedede the Rock", character: "King Dedede", Category: "Defense", slot_number: 9)
Contestant.create(name: "Charizard the Rock", character: "Charizard", Category: "Defense", slot_number: 1)
Contestant.create(name: "Bowser the Rock", character: "Charizard", Category: "Defense", slot_number: 1)
Contestant.create(name: "Mr. Make & Watch", character: "Mr. Game & Watch", Category: "", slot_number: 8)
Contestant.create(name: "Trade Off Watch", character: "Mr. Game & Watch", Category: "", slot_number: 7)
Contestant.create(name: "Kinkay", character: "Mii Swordfighter", Category: "Mii", slot_number: 1)
Contestant.create(name: "Emerson", character: "Mii Swordfighter", Category: "Mii", slot_number: 0)
Contestant.create(name: "e-girl", character: "Mii Swordfighter", Category: "Mii", slot_number: 0)
Contestant.create(name: "Buffdunker", character: "Mii Basher", Category: "Mii", slot_number: 0)
Contestant.create(name: "Fedra", character: "Mii Basher", Category: "Mii", slot_number: 0)
Contestant.create(name: "Smols", character: "Mii Basher", Category: "Mii", slot_number: 0)
Contestant.create(name: "Jack Sparrow", character: "Mii Gunner", Category: "Mii", slot_number: 0)
Contestant.create(name: "Hello Kitty", character: "Mii Gunner", Category: "Mii", slot_number: 0)
Contestant.create(name: "Aaron Burr", character: "Mii Gunner", Category: "Mii", slot_number: 0)
Contestant.create(name: "Exploshi", character: "Yoshi", Category: "", slot_number: 1)
Contestant.create(name: "Strong Diddy", character: "Diddy Kong", Category: "Basher", slot_number: 9)
Contestant.create(name: "Priestess Aran", character: "Samus", Category: "Healer", slot_number: 9)
Contestant.create(name: "Priest Mew", character: "Mewtwo", Category: "Healer", slot_number: 9)
Contestant.create(name: "Anemia", character: "Roy", Category: "Speed/healer", slot_number: 9)
Contestant.create(name: "Batty Marth", character: "Marth", Category: "Item specialist", slot_number: 4)
Contestant.create(name: "Shieldy Marth", character: "Marth", Category: "", slot_number: 8)
Contestant.create(name: "Lu Cena", character: "Lucina", Category: "Basher", slot_number: 9)
Contestant.create(name: "Bee", character: "Ness", Category: "", slot_number: 8)
Contestant.create(name: "Lu Cena", character: "Lucina", Category: "", slot_number: 9)
Contestant.create(name: "Thicc Daisy", character: "Peach", Category: "Defense", slot_number: 8)
Contestant.create(name: "Tough Iggy", character: "Bowser Jr.", Category: "Basher", slot_number: 8)
Contestant.create(name: "Mixed Specialist", character: "Pac-man", Category: "", slot_number: 8)
Contestant.create(name: "Stinky Wario", character: "Wario", Category: "", slot_number: 8)
Contestant.create(name: "Pretty Wario", character: "Wario", Category: "", slot_number: 9)
Contestant.create(name: "Sniper Mage", character: "Robin", Category: "", slot_number: 2)
Contestant.create(name: "Everywhere Robot", character: "R.O.B.", Category: "Jumper", slot_number:)
Contestant.create(name: "OP Bayo", character: "Bayonetta", Category: "Buffed Standard", slot_number:)
