Contestant.create(name: "Dedede the Rock", character: "King Dedede", Category: "Defense", slot_number: 9)
Contestant.create(name: "Charizard the Rock", character: "Charizard", Category: "Defense", slot_number: 1)
Contestant.create(name: "Bowser the Rock", character: "Charizard", Category: "Defense", slot_number: 1)
Contestant.create(name: "Mr. Make & Watch", character: "Mr. Game & Watch", Category: "", slot_number: 8)
Contestant.create(name: "Trade Off Watch", character: "Mr. Game & Watch", Category: "", slot_number: 7)
Contestant.create(name: "Kinkay", character: "Mii Swordfighter", Category: "Mii", slot_number: 1)
Contestant.create(name: "Emerson", character: "Mii Swordfighter", Category: "Mii", slot_number: 0)
Contestant.create(name: "e-girl", character: "Mii Swordfighter", Category: "Mii", slot_number: 0)
Contestant.create(name: "Buffdunker", character: "Mii Basher", Category: "Mii", slot_number: 0)
Contestant.create(name: "Fedra", character: "Mii Basher", Category: "Mii", slot_number: 0)
Contestant.create(name: "Smols", character: "Mii Basher", Category: "Mii", slot_number: 0)
Contestant.create(name: "Jack Sparrow", character: "Mii Gunner", Category: "Mii", slot_number: 0)
Contestant.create(name: "Hello Kitty", character: "Mii Gunner", Category: "Mii", slot_number: 0)
Contestant.create(name: "Aaron Burr", character: "Mii Gunner", Category: "Mii", slot_number: 0)
Contestant.create(name: "Exploshi", character: "Yoshi", Category: "", slot_number: 1)
Contestant.create(name: "Strong Diddy", character: "Diddy Kong", Category: "Basher", slot_number: 9)
Contestant.create(name: "Priestess Aran", character: "Samus", Category: "Healer", slot_number: 9)
Contestant.create(name: "Priest Mew", character: "Mewtwo", Category: "Healer", slot_number: 9)
Contestant.create(name: "Anemia", character: "Roy", Category: "Speed/healer", slot_number: 9)
Contestant.create(name: "Batty Marth", character: "Marth", Category: "Item specialist", slot_number: 4)
Contestant.create(name: "Shieldy Marth", character: "Marth", Category: "", slot_number: 8)
Contestant.create(name: "Lu Cena", character: "Lucina", Category: "Basher", slot_number: 9)
Contestant.create(name: "Bee", character: "Ness", Category: "", slot_number: 8)
Contestant.create(name: "Lu Cena", character: "Lucina", Category: "", slot_number: 9)
Contestant.create(name: "Thicc Daisy", character: "Peach", Category: "Defense", slot_number: 8)
Contestant.create(name: "Tough Iggy", character: "Bowser Jr.", Category: "Basher", slot_number: 8)
Contestant.create(name: "Mixed Specialist", character: "Pac-man", Category: "", slot_number: 8)
Contestant.create(name: "Stinky Wario", character: "Wario", Category: "", slot_number: 8)
Contestant.create(name: "Pretty Wario", character: "Wario", Category: "", slot_number: 9)
Contestant.create(name: "Sniper Mage", character: "Robin", Category: "", slot_number: 2)
Contestant.create(name: "Everywhere Robot", character: "R.O.B.", Category: "Jumper", slot_number:)
Contestant.create(name: "OP Bayo", character: "Bayonetta", Category: "Buffed Standard", slot_number:)
Contestant.create(name: "OP Man", character: "Megaman", Category: "Buffed Standard", slot_number:)
Contestant.create(name: "OP Link", character: "Link", Category: "Buffed Standard", slot_number: 1)
Contestant.create(name: "Fast Pit", character: "Pit", Category: "Speed", slot_number: 8)
Contestant.create(name: "Meteor Shulk", character: "Shulk", Category: "", slot_number:)
Contestant.create(name: "Not Wolf", character: "Fox", Category: "", slot_number: 9)
Contestant.create(name: "other fox", character: "Fox", Category: "", slot_number: 8)
Contestant.create(name: "Jumpy Mac", character: "Little Mac", Category: "Jumper", slot_number: 8)
Contestant.create(name: "Basher", character: "Kirby", Category: "Basher", slot_number:)
Contestant.create(name: "Speedkachu", character: "Pikachu", Category: "Speed", slot_number:)
Contestant.create(name: "Land Lubber Luigi", character: "Luigi", Category: "", slot_number: 8)
Contestant.create(name: "Rosalina and Luma", character: "Rosalina and Luma", Category: "Standard", slot_number: 0)
Contestant.create(name: "Corrin", character: "Corrin", Category: "Standard", slot_number: 0)
Contestant.create(name: "Zero Suit Samus", character: "Zero Suit Samus", Category: "Standard", slot_number: 0)
Contestant.create(name: "Ryu", character: "Ryu", Category: "Standard", slot_number: 0)
Contestant.create(name: "Lucarengee", character: "Lucario", Category: "", slot_number: 7)
Contestant.create(name: "MirrorPuff", character: "Jigglypuff", Category: "", slot_number: 0)
Contestant.create(name: "Woke Alph", character: "Olimar", Category: "", slot_number: 9)
Contestant.create(name: "Fierce Diety", character: "Link", Category: "", slot_number: 9)
Contestant.create(name: "Fast Doc", character: "Dr. Mario", Category: "Speed", slot_number: 9)
Contestant.create(name: "Trade Off Doc", character: "Dr. Mario", Category: "Trade Off", slot_number: 8)
Contestant.create(name: "He Fitness Basher", character: "Wii Fitness Trainer", Category: "Basher", slot_number: 8)
Contestant.create(name: "She Fitness Basher", character: "Wii Fitness Trainer", Category: "Basher", slot_number: 7)
Contestant.create(name: "Loose Gannon", character: "Ganondorf", Category: "Speed", slot_number: 9)
Contestant.create(name: "DPS Ganon", character: "Ganondorf", Category: "Basher", slot_number: 8)
Contestant.create(name: "Jumpy Dog", character: "Duck Hunt", Category: "Jumper", slot_number: 8)
Contestant.create(name: "Slippery Kong", character: "Donkey Kong", Category: "Speed", slot_number: 8)
Contestant.create(name: "Leader of the Bunch", character: "Donkey Kong", Category: "", slot_number: 9)
Contestant.create(name: "Sheik A", character: "Sheik", Category: "", slot_number: 9)
Contestant.create(name: "Sheik B", character: "Sheik", Category: "", slot_number: 8)
Contestant.create(name: "Flinchless Falcon", character: "Captain Falcon", Category: "", slot_number: 9)
Contestant.create(name: "Basher Toon Link", character: "Toon Link", Category: "Basher", slot_number: 9)
Contestant.create(name: "2fast Knight", character: "Meta Knight", Category: "Speed", slot_number: 9)

Matchup.create(contestant_one_id: Contestant.find_by(name: "Slippery Kong"), contestant_two_id: Contestant.find_by(name: "Priestess Aran"), youtube_link: "https://youtu.be/SrVkpqBTpM4", outcome: "2-0")

Matchup.create(contestant_one_id: Contestant.find_by(name: "Mixed Specialist"), contestant_two_id: Contestant.find_by(name: "Smols"), youtube_link: "https://youtu.be/V60SWv9yINA", outcome: "0-2")

Matchup.create(contestant_one_id: Contestant.find_by(name: "Stinky Wario"), contestant_two_id: Contestant.find_by(name: "Tough Iggy"), youtube_link: "https://youtu.be/B7odOj7dqSg", outcome: "0-2")

Matchup.create(contestant_one_id: Contestant.find_by(name: "Dedede the Rock"), contestant_two_id: Contestant.find_by(name: "DPS Ganon"), youtube_link: "https://youtu.be/hSe4d8dFkVc")

Matchup.create(contestant_one_id: Contestant.find_by(name: "e-girl"), contestant_two_id: Contestant.find_by(name: "Loose Gannon"), youtube_link: "https://youtu.be/5VHEJnLJR_A", outcome: "2-0")

Matchup.create(contestant_one_id: Contestant.find_by(name: "Exploshi", contestant_two_id: Contestant.find_by(name: "She Fitness Basher"), youtube_link: "https://youtu.be/F8cRE-NFkMY", outcome: "2-0"))

Matchup.create(contestant_one_id: Contestant.find_by(name: "Lu Cena"), contestant_two_id: Contestant.find_by(name: "Bowser the Rock"), youtube_link: "https://youtu.be/EY9KVycbGfU", outcome: "2-1")
